name: vmihalachi_flutter
description: Landing page for vmihalachi.com
author: Vlad Mihalachi <vmihalachi@outlook.com>
homepage: https://github.com/vmihalachi/vmihalachi_flutter

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # url_launcher: 5.1.4
flutter:
