name: vmihalachi_flutter
description: Landing page for vmihalachi.com
author: Vlad Mihalachi <vmihalachi@outlook.com>
homepage: https://github.com/vmihalachi/vmihalachi_flutter

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # url_launcher: 5.1.4

flutter:
  fonts:
    - family: circular
      fonts:
        - asset: web/assets/fonts/circular-medium.ttf
#        - asset: web/assets/fonts/circular-mediumitalic.ttf
#        - asset: web/assets/fonts/circular-black.ttf
#        - asset: web/assets/fonts/circular-blackitalic.ttf
#        - asset: web/assets/fonts/circular-bold.ttf
#        - asset: web/assets/fonts/circular-bolditalic.ttf
#        - asset: web/assets/fonts/circular-book.ttf
#        - asset: web/assets/fonts/circular-bookitalic.ttf