name: vmihalachi_flutter
description: Example for the simple_animations package
author: Felix Blaschke <felix@felix-blaschke.de>
homepage: https://github.com/felixblaschke/simple_animations

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: 5.1.4
flutter:
  assets:
    - preview.png
